export const userConstants = {
  LOGOUT: "LOGOUT",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGIN: "LOGIN",

  SET_YEAR: "SET_YEAR",
};
