export const userConstants = {
  REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  LOGIN_REQUEST: "USER_REGISTER_FAILURE",
  LOGIN_SUCCESS: "USER_REGISTER_FAILURE",
  LOGIN_FAILURE: "USER_REGISTER_FAILURE",

  LOGOUT: "USER_LOGOUT",
};
