export const userConstants = {
  LOGOUT: "LOGOUT",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAIL",

  REGISTER: "REGISTER",
  LOGIN: "LOGIN",

  SELECT_YEAR: "SELECT_YEAR",
};
